SELECT
  prestamos.id_prestamo,
  clientes.id_cliente,
  clientes.nombre,
  clientes.cedula,
  clientes.telefono,
  clientes.direccion,
  clientes.foto_url,
  prestamos.monto,
  prestamos.interes,
  prestamos.cant_cuotas,
  prestamos.frecuencia_pago,
  prestamos.fecha_inicio,
  prestamos.fecha_vencimiento,
  prestamos.estado
FROM
  (
    prestamos
    JOIN clientes ON ((prestamos.id_cliente = clientes.id_cliente))
  );